#!/bin/bash

echo "Welcome to Betabot."
echo ""
echo "Commands:"
echo "betabot		Start betabot"
echo "stop_betabot	Stop betabot"
echo "off		Switch off"
echo "reboot		Reboot"
echo "go		Open editor"
echo "config		Open motor controller configurator"
echo "cam		Show camera preview"
echo "web		Open web browser"
echo 
