#!/bin/bash

# Installs the things needed for Betabot to run on a Raspberry Pi 3.
echo "Installing Betabot."

# Update
if [ "$1" != "quick" ]; then
	echo ""
	echo "Updating system."
	sudo apt-get update
	sudo apt-get upgrade
	echo "Done."
fi

# Install
echo ""
echo "Installing requirements."
sudo apt-get install -y python-picamera python3-picamera
sudo apt-get install -y python-opencv
sudo apt-get install -y git
git config --global push.default simple
sudo pip install -q keyboard
sudo pip install -q picamera[array]
sudo pip install -q python_Xlib
sudo pip install -q pynput
sudo pip3 install -q pyserial
sudo pip3 install -q pynput
sudo pip3 install -q python_Xlib
sudo pip3 install -q python_Xlib --upgrade
sudo pip3 install -q six
sudo pip3 install -q six --upgrade
echo "Done."

# Install the global Betabot script link
echo ""
echo "Installing system scripts."
sudo ln /home/pi/betabot/start /bin/start -fs
sudo ln /home/pi/betabot/scripts/work /bin/work -fs
sudo ln /home/pi/betabot/scripts/reboot /bin/reboot -fs
sudo ln /home/pi/betabot/scripts/off /bin/off -fs
sudo ln /home/pi/betabot/scripts/cam /bin/cam -fs
sudo ln /home/pi/betabot/scripts/config /bin/config -fs
sudo ln /home/pi/betabot/scripts/web /bin/web -fs
sudo ln /home/pi/betabot/scripts/stop /bin/stop -fs
sudo cp rc.local /etc/rc.local # Start on system startup (overrides rc.local)
if [ "$1" != "quick" ]; then
	echo "cd betabot" >> ~/.bashrc
	echo "welcome" >> ~/.bashrc
fi
echo "Done."

# Raspberry Pi 3 has broken UART serial output pins because Bluetooth uses the serial line and breaks it. 
# If you need to use it, you can disable Bluetooth by uncommenting these lines and running install.
#echo ""
#echo "Enabling serial bus."
#sudo bash -c "echo 'dtoverlay=pi3-disable-bt' >> /boot/config.txt"
#echo "Done."

# Install Raspicam to capture video from C
#./install_camera

# Install TensorFlow
#./install_tensorflow

# Install hdf5 for large model saving
# This takes about half an hour.
#./install_hdf5

# Done
echo ""
echo "All done. Enjoy Betabot."
