#!/bin/bash

# Install hdf5 for large model saving
echo ""
echo "Installing hdf5. This takes nearly 30 minutes on the pi."
sudo apt-get install -y hdf5-tools libhdf5-serial-dev
sudo pip install h5py

# Done
echo ""
echo "Done."

