#!/bin/bash

sudo apt-get install -y curl
curl http://www.linux-projects.org/listing/uv4l_repo/lrkey.asc | sudo apt-key add -
echo 'deb http://www.linux-projects.org/listing/uv4l_repo/raspbian/ jessie main' >> /etc/apt/sources.list
sudo apt-get update
sudo apt-get install -y uv4l uv4l-raspicam
sudo apt-get install -y uv4l-raspicam-extras
sudo service uv4l_raspicam restart
# sudo raspi-config
# sudo rpi-update
sudo apt-get install -y uv4l-server 
sudo apt-get install -y uv4l-uvc
sudo apt-get install -y uv4l-xscreen
sudo apt-get install -y uv4l-mjpegstream
sudo apt-get install -y uv4l-webrtc
  
    

# Install Raspicam to capture video from C
echo "Installing Raspicam."
git clone https://github.com/cedricve/raspicam &&
cd raspicam && 
mkdir build &&
cd build &&
cmake .. &&
make &&
sudo make install &&
sudo ldconfig &&
cd .. &&
cd ..

# Done
echo "Done."

