#!/bin/bash

# Installs the things needed for Betabot to run on a Raspberry Pi.
echo "Installing Betabot."
cd /home/pi/betabot/install

# Do full install if "quick" isn't given on commandline
if [ "$1" != "quick" ]; then
	# Update system
	echo ""
	echo "Updating system."
	sudo apt-get update -y
	sudo apt-get upgrade -y
	echo "Done."

	# Install path and welcome on startup
	echo "PATH=$PATH:/home/pi/betabot/scripts" >> ~/.bashrc
	echo "cd betabot" >> ~/.bashrc
	echo "scripts/welcome" >> ~/.bashrc
fi

# Install
echo ""
echo "Installing requirements."

# You may need to put pip here to have it found when used with sudo
#sudo ln -s /home/tom/anaconda3/bin/pip /usr/bin/pip

sudo apt-get install -y python-picamera python3-picamera
sudo apt-get install -y python-opencv
sudo apt-get install -y dfu-util
sudo apt-get install -y flite
sudo apt-get install -y git
sudo apt-get install -y geany
sudo apt-get install -y python-visual
sudo apt-get install -y screen
sudo apt-get install -y eog
sudo apt-get install -y python-dev
sudo apt-get -y autoremove

git config --global push.default simple
git config --global user.name "Betabot"
git config --global user.email "hatsmagee@gmail.com"

# Ubuntu has start and stop commands that just break the system. Great. So let's move them away.
sudo mv /sbin/start /sbin/bad_start
sudo mv /sbin/stop /sbin/bad_stop

echo "Installing python modules."
sudo pip install -q keyboard
sudo pip install -q picamera[array]
sudo pip install -q python_Xlib
sudo pip install -q python_Xlib --upgrade
sudo pip install -q pynput
sudo pip install -q pyserial
sudo pip install -q six
sudo pip install -q six --upgrade
sudo pip install -q asyncio
sudo pip install -U socketIO-client
sudo pip install -q websockets
sudo pip install -q python-osc
echo "Done."

# Install utilities and startup
./install_utilities

# Install ffmpeg
./install_ffmpeg

# Clean up stuff we don't need
./install_cleanup

# Install camera utilities like GStreamer to stream and Raspicam to capture
./install_camera  

# Install TensorFlow
#./install_tensorflow

# Install hdf5 for large model saving. This takes about half an hour.
#./install_hdf5

# Install configurator
../scripts/web "https://chrome.google.com/webstore/detail/betaflight-configurator/kdaghagfopacdngbohiknlhcocjccjao"

# Check out submodules
git submodule update --recursive --init

# Raspberry Pi 3 has broken UART serial output pins because Bluetooth uses the serial line and breaks it. 
# If you need to use it, you can disable Bluetooth by uncommenting these lines and running install.
#echo ""
#echo "Enabling serial bus."
#sudo bash -c "echo 'dtoverlay=pi3-disable-bt' >> /boot/config.txt"
#echo "Done."

# Done
echo ""
echo "All done. Enjoy Betabot."

# Todo:
echo "sudo raspi-config set keyboard to US"
echo "sudo raspi-config enable camera"
echo "sudo raspi-config enable I2C"
echo "sudo raspi-config enable SSH"

