#!/bin/bash

sudo apt-get install -y libboost-all-dev

# Create a 1 gig swap file for ubuntu
sudo dd if=/dev/zero of=/swapfile bs=1G count=4
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile

sudo apt-get install -y build-essential cmake libatlas-dev libavcodec-dev libavformat-dev libgtk2.0-dev libjpeg-dev libswscale-dev liblapack-dev

sudo pip install face_recognition

