#!/bin/bash

echo "Installing ffmpeg."

# Install espeak
sudo apt-get install espeak

# Install ALSA
wget ftp://ftp.alsa-project.org/pub/lib/alsa-lib-1.0.25.tar.bz2
tar xjf alsa-lib-1.0.25.tar.bz2
cd alsa-lib-1.0.25
./configure --host=arm-unknown-linux-gnueabi
make -j4
sudo make install

# Install x264
cd ..
git clone git://git.videolan.org/x264
cd x264
./configure --host=arm-unknown-linux-gnueabi --enable-static --disable-opencl
make -j4
sudo make install

# Install ffmpeg
cd ..
git clone https://github.com/FFmpeg/FFmpeg.git
cd FFmpeg
./configure --arch=armel --target-os=linux --enable-gpl --enable-libx264 --enable-nonfree --extra-libs=-ldl
make -j4
sudo make install

echo "Done."
