#!/bin/bash

# Install GStreamer for streaming video over the net
echo "Installing GStreamer."
sudo apt-get install -y --fix-missing gstreamer1.0

#echo "Installing FlyCapture for Point Grey camera"
#sudo apt-get install libraw1394-11 libgtkmm-2.4-1v5 libglademm-2.4-1v5 libgtkglextmm-x11-1.2-dev libgtkglextmm-x11-1.2 libusb-1.0-0
#unzip flycapture.2.9.3.43_armhf.tar.gz
#cd flycapture.2.9.3.43_armhf
#sudo flycap2-conf
#sudo sh install_flycapture.sh

# Install UV4L for Raspberry
echo "Installing UV4L."
sudo apt-get install -y curl
curl http://www.linux-projects.org/listing/uv4l_repo/lrkey.asc | sudo apt-key add -
sudo bash -c "echo 'deb http://www.linux-projects.org/listing/uv4l_repo/raspbian/ jessie main' >> /etc/apt/sources.list"
sudo apt-get update -y
sudo apt-get install -y uv4l uv4l-raspicam
sudo apt-get install -y uv4l-raspicam-extras
sudo service uv4l_raspicam restart

# echo "Installing UV4L Utilities."
# sudo raspi-config
# sudo rpi-update
# sudo apt-get install -y uv4l-server 
# sudo apt-get install -y uv4l-uvc
# sudo apt-get install -y uv4l-xscreen
# sudo apt-get install -y uv4l-mjpegstream
# sudo apt-get install -y uv4l-webrtc
  
# Install Raspicam from source to fix it and capture video from C
echo "Installing Raspicam."
sudo apt-get install -y cmake
git clone https://github.com/cedricve/raspicam &&
cd raspicam && 
mkdir build &&
cd build &&
cmake .. &&
make &&
sudo make install &&
sudo ldconfig &&
cd .. &&
cd ..

# Done
echo "Done."

