#!/bin/bash

# Installs the things needed for Betabot to run on a Raspberry Pi 3.
echo "Installing utilities."

sudo ln /home/pi/betabot/start /home/pi/betabot/scripts/start -fs
sudo cp /home/pi/betabot/install/rc.local /etc/rc.local # Start on system startup (overrides rc.local)
sudo cp /home/pi/betabot/install/autostart /home/pi/.config/lxsession/LXDE-pi/autostart #(start terminal)
echo "Done."
