#!/bin/bash

# Install Betabot.
# Installs the things needed for Betabot to run on a Raspberry Pi 3.
echo "Installing Betabot."

# Update
echo ""
echo "Updating system."
sudo apt-get update
sudo apt-get upgrade
echo "Done."

# Install git
echo ""
echo "Installing requirements."
sudo apt-get install -y git
git config --global push.default simple
sudo pip install -q python_Xlib
sudo pip install -q pynput
echo "Done."

# Install the global Betabot script link
echo ""
echo "Installing system scripts."
sudo ln /home/pi/betabot/betabot /bin/betabot -fs
sudo ln /home/pi/betabot/install/go /bin/go -fs
sudo ln /home/pi/betabot/install/web /bin/web -fs
sudo cp rc.local /etc/rc.local # Start on system startup (overrides rc.local)
echo "Done."

# Disable Bluetooth. Raspberry Pi 3 needs its Bluetooth disabling.
# Because Bluetooth uses the serial line and breaks it. 
echo ""
echo "Enabling serial bus."
sudo bash -c "echo 'dtoverlay=pi3-disable-bt' >> /boot/config.txt"
echo "Done."

# Install Raspicam to capture video from C
./install_camera

# Install hdf5 for large model saving
echo ""
echo "Installing hdf5. This takes nearly 30 minutes on the pi."
sudo apt-get install -y hdf5-tools libhdf5-serial-dev
sudo pip install h5py

# Done
echo ""
echo "All done. Enjoy Betabot."

