#!/bin/bash

echo "Stopping Betabot."
# Kill all other old instances of start other than ourselves
for PID in `ps ax | grep '[s]tart' | awk ' { print $1;}'`; do
	echo $PID
	echo $BASHPID
	if [ $PID != $BASHPID ] ; then
    		kill -9 $PID
	fi
done

sudo killall -9 python 2> /dev/null
sudo killall -9 python2.7 2> /dev/null
sudo killall -9 python3 2> /dev/null
if pgrep python; then
echo "Error stopping Betabot, python is still running."
else	
echo "Stopped."
fi
