#!/bin/bash

# Where are we sending this to?
DEST=meetzippy.com

# Sound
gst-launch-1.0 alsasrc ! opusenc bitrate=20000 ! rtpopuspay ! udpsink host=$DEST port=5002 #&

# Video
raspivid --nopreview --width 1280 --height 768 --intra 10 --framerate 10 --bitrate 500000 -ex fixedfps -awb on --ISO 1800 --timeout 0 -o - | gst-launch-1.0 -v fdsrc ! h264parse ! rtph264pay config-interval=10 pt=126 ! udpsink host=$DEST port=5004

