#!/bin/bash

echo "Welcome to Betabot."
echo ""
echo "Commands:"
echo ""
echo "start		Start betabot"
echo "stop		Stop betabot"
echo ""
echo "off		Switch off"
echo "reboot		Reboot"
echo ""
echo "work		Work on betabot in editor"
echo "config		Open configurator"
echo ""
echo "cam		Show camera preview"
echo "vision		Start vision processing"
echo "video		Start video transmission"
echo ""
echo 'web "search"	Open web browser'
echo 
