#!/bin/bash

echo "Welcome to Betabot."
echo ""
echo "Commands:"
echo "betabot		Start betabot"
echo "stop		Stop betabot"
echo "off		Switch off"
echo "reboot		Reboot"
echo "work		Work on betabot in editor"
echo "config		Open motor controller configurator"
echo "cam		Show camera preview"
echo "web		Open web browser"
echo 
