#!/bin/bash

# Start editing
if [ -d "/home/pi/betabot" ]; then
	cd /home/pi/betabot
	geany source/bot.py source/walk.py source/functions.py source/motors.py &
else
	/Applications/Sublime\ Text.app/Contents/MacOS/Sublime\ Text . 2> /dev/null &
fi
